#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    mkdir -p /etc/pullconf
    chmod 755 /etc/pullconf

    touch /etc/pullconf/environment
    chmod 600 /etc/pullconf/environment

    mkdir -p /var/lib/pullconf
    chmod 750 /var/lib/pullconf

    mkdir -p /var/log/pullconf
fi

#DEBHELPER#
